from typing import Dict, List

catalogue: List[Dict[str, str | int]] = [{"name": "Item 0", "price": 10,
                                          "max_allowed_quantity": 20},
                                         {"name": "Item 1", "price": 11,
                                             "max_allowed_quantity": 21},
                                         {"name": "Item 2", "price": 12,
                                             "max_allowed_quantity": 22},
                                         {"name": "Item 3", "price": 13,
                                             "max_allowed_quantity": 23},
                                         {"name": "Item 4", "price": 14,
                                             "max_allowed_quantity": 24},
                                         {"name": "Item 5", "price": 15,
                                             "max_allowed_quantity": 25},
                                         {"name": "Item 6", "price": 16,
                                             "max_allowed_quantity": 26},
                                         {"name": "Item 7", "price": 17,
                                             "max_allowed_quantity": 27},
                                         {"name": "Item 8", "price": 18,
                                             "max_allowed_quantity": 28},
                                         {"name": "Item 9", "price": 19,
                                          "max_allowed_quantity": 29}]
